name: Build Void Linux packages

on:
  push:
    branches:
      - source
    paths:
      - "void/**"
  workflow_dispatch:

jobs:
  init:
    name: Initialize Void Linux package builds
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-packages.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Find all Void Linux packages
        id: find-packages
        run: |
          find void/srcpkgs -mindepth 1 -maxdepth 1 \
            | sed 's|^void/srcpkgs/||' \
            | jq -R \
            | jq -cs '{ "package": . }' \
            > matrix.json
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  build:
    name: Build all packages
    runs-on: ubuntu-latest
    needs:
      - init
    strategy:
      matrix: ${{ fromJson(needs.init.outputs.matrix) }}

    steps:
      - name: Install latest version of xbps
        run: |
          curl -L https://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz -o xbps.tar.xz
          tar -xJvf xbps.tar.xz
          rm xbps.tar.xz
          echo "$(pwd)/usr/bin" >> $GITHUB_PATH

      - name: Checkout void-packages repository
        uses: actions/checkout@v4
        with:
          path: void-packages
          repository: void-linux/void-packages

      - name: Checkout my repository
        uses: actions/checkout@v4
        with:
          path: rangho-packages

      - name: Copy custom package data to void-repository
        run: |
          cat rangho-packages/void/common/shlibs >> void-packages/common/shlibs
          cp -r rangho-packages/void/srcpkgs/* void-packages/srcpkgs/

      - name: Build package
        run: |
          cd void-packages
          ./xbps-src zap
          ./xbps-src binary-bootstrap
          ./xbps-src pkg "${{ matrix.package }}"

      - name: Upload package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: void-${{ matrix.package }}
          path: void-packages/hostdir/binpkgs/${{ matrix.package }}*.xbps

  deploy:
    name: Deploy all packages
    runs-on: ubuntu-latest
    needs:
      - init
      - build
    env:
      XBPS_ARCH: x86_64
      XBPS_TARGET_ARCH: x86_64

    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Install latest version of xbps
        run: |
          curl -L https://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz -o xbps.tar.xz
          tar -xJvf xbps.tar.xz
          rm xbps.tar.xz
          echo "$(pwd)/usr/bin" >> $GITHUB_PATH

      - name: Copy all packages into void directory
        run: |
          mkdir -p void
          cp ./artifacts/*/*.xbps ./void

      - name: Add all packages to the repository
        run: |
          cd void
          for pkg in *.xbps; do
            xbps-rindex --add $pkg
          done

      - name: Remove all packages that are no longer built
        env:
          PACKAGES: ${{ needs.init.outputs.matrix }}
        run: |
          mv ./void ./void-previous
          mkdir ./void
          cp ./void-previous/${XBPS_ARCH}-repodata ./void/${XBPS_ARCH}-repodata
          for pkg in $(echo "$PACKAGES" | jq -r '.package[]'); do
            pkgver=$(xbps-query --repository="$(pwd)/void-previous" --show $pkg --property pkgver)
            mv $(pwd)/void-previous/$pkgver.$XBPS_ARCH.xbps $(pwd)/void
          done

      - name: Sign all packages in the repository
        run: |
          echo "${{ secrets.RANGHO_REPOSITORY_SIGNING_KEY }}" > private.pem
          xbps-rindex \
            --privkey private.pem \
            --sign \
            --signedby "RangHo Lee <hello@rangho.me>" \
            "$(pwd)/void"
          for pkg in ./void/*.xbps; do
            xbps-rindex --privkey private.pem --sign-pkg $pkg
          done

      - name: Clean up repositories
        run: |
          xbps-rindex --hashcheck --clean "$(pwd)/void"
          xbps-rindex --remove-obsoletes "$(pwd)/void"

      - name: Push updated repository to remote
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Upload Void Linux packages
          file_pattern: "void/*"
          push_options: "--force"
