name: Update repository

on:
  - push
  - workflow_dispatch

jobs:
  build-android:
    name: Build Android applications
    uses: ./.github/workflows/build-android.yml
    secrets: inherit

  build-void:
    name: Build Void Linux packages
    uses: ./.github/workflows/build-void.yml
    secrets: inherit

  deploy:
    name: Deploy everything to Netlify
    if: github.ref == 'refs/heads/main'
    needs:
      - build-void
      - build-android
    uses: ./.github/workflows/deploy-netlify.yml
    secrets: inherit
